volumes:
  dev-db:
  dev-pgadmin:

services:
  app:
    container_name: europe-scouts
    # image: europe.scouts:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    links:
      - db
    ports:
      - "3000:3000"

  db:
    container_name: europe-scouts-db
    image: postgres:16
    volumes:
      - dev-db:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

    # networks:
    #   keycloak:

  # pgadmin:
  #   container_name: europe-scouts-pgadmin
  #   image: docker.io/dpage/pgadmin4:latest
  #   # container_name: pgadmin4_container
  #   # restart: always
  #   restart: unless-stopped
  #   volumes:
  #     - dev-pgadmin:/var/lib/pgadmin
  #   ports:
  #     - "8080:80"
  #   env_file:
  #     - .env
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   links:
  #     - db
