export enum AuthStatus {
  UNAUTHENTICATED = "UNAUTHENTICATED",
  VERIFICATION = "VERIFICATION",
  ONBOARDING = "ONBOARDING",
  AUTHENTICATED = "AUTHENTICATED"
}

// export enum AuthStatus {
//   UNAUTHENTICATED,
//   ONBOARDING,
//   AUTHENTICATED
// }