volumes:
  postgres-data:
  pgadmin:

services:
  scouts.europe:
    container_name: dev-europe-scouts
    build: 
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    container_name: dev-europe-scouts-db
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    # environment:
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_DB: ${POSTGRES_DB}

  pgadmin:
    container_name: dev-pgadmin
    image: docker.io/dpage/pgadmin4:latest
    # container_name: pgadmin4_container
    # restart: always
    restart: unless-stopped
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"
    env_file:
      - .env
    # environment:
    #   PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
    #   PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    # volumes:
    #   - pgadmin-data:/var/lib/pgadmin

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  papercut_smtp:
    container_name: papercut
    image: changemakerstudiosus/papercut-smtp:latest
    ports:
      - '25:25'
      - '8025:80'
    restart: unless-stopped